# Linear Regression from Scratch

In [84]:
# Importing Libraries

import numpy as np
from sklearn.model_selection import train_test_split
from scipy import optimize
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

true_theta = [0.5,0.3,0.2]
y= 0.5 + 0.3X1 +0.2X2
x = [1,0.1,0.4]

y = wTx  [0.5 0.3 0.2] transpose([1 0.1 0.4])

(0.5*1) + (0.3*0.1) +(0.2*0.4)   

we explicitly add a column of ones to account for the intercept term.

**intercept :** it is the value of the ordinate (y-axis) when the abscissa(x-axis) is 0. The presence of an intercept allows you to translate the line along the y axis.

In [87]:
# Creating Data

true_thetas = np.array([0.5,0.2,0.3])    #intercept,theta 1, theta 2 (plane)   - data will lie on that plane.
x = np.random.normal(0,1,size = (500,2))      #first argument is mean of normal distribution and second argument is standard deviation
noise = np.random.normal(0,0.05,size = (500,1))    #creating noise


In [88]:
# Appending a column of Ones to x

ones = [1] *500        # it will create vector of one of length 500
ones = np.array(ones)
ones = ones[:,np.newaxis]      #converting a 0-d array to 1-d array with one column.
print(ones.shape)
data = np.append(ones,x,axis = 1)    #appending vector one to x vector so that ones column comes first
data.shape

(500, 1)


(500, 3)

In [89]:
print(data)

[[ 1.          1.61780543  0.4585674 ]
 [ 1.         -1.27813273 -0.397673  ]
 [ 1.         -1.11630502 -0.35851529]
 ...
 [ 1.         -0.42871946  0.26738871]
 [ 1.          0.6636005   0.36007049]
 [ 1.          0.23589036  0.10000402]]


In [90]:
noise.shape

(500, 1)

 **Creating the Target Variable**

In [91]:
y = np.dot(data,true_thetas.T)[:,np.newaxis] +noise 
print(y.shape)

(500, 1)


**Aim :** given the data, what are the values of the parameters that result in the minimum sum of errors.(known as fitting)
we need training and testing data.

In [93]:
x_train,x_test,y_train,y_test = train_test_split(data,y,test_size=0.2,random_state=0)

#it splits the data randomly, random_state=0, we should get same splits everytime. 
#if we don't specify this, we will get random splits everytime and the performance of our model will vary.


In [94]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(400, 3)
(100, 3)
(400, 1)
(100, 1)


In [95]:
def cost(weights,x,y):
    residual = y-np.dot(x,weights.T)[:,np.newaxis]
    return residual.ravel()

**residual :** is the amount of error made by the model for that particular point (y-prediction).

**ravel :** we need to ravel the residuals because the least squares method expects a zero dimensional array and np.dot gives a 1-d array.

## Finding the right parameters by minimizing the sum of square of errors(residuals)

In [96]:
initial_weights =  [1,1,1]  # parameters - intercept,theta1,theta2
kwargs = {'x': x_train,'y':y_train}
results = optimize.least_squares(cost,initial_weights,kwargs=kwargs)         #kwargs=kwargs   for the third argument

#when the third argument argument of this function is solver since we did not specify kwargs=kwargs, the function assumes that 
#we passed kwargs as a solver which is incorrect.

print(results.x)   #values of the parameters which minimize the error. values obtained from the data.

[0.50529743 0.19854395 0.29835565]


In [98]:
print(true_thetas)     # Actual value of the parameters.

[0.5 0.2 0.3]


**The predicted parameter values is very close to the true values because our data was generated using the true values. 
Generally, we do not know the true parameter values used to generate the data. Therefore,the task of fitting the model referes to estimating the true values used to generate the data.**

In [99]:
# Obtaining predictions from the fitted parameters for the training data

fitted_parameters = np.array(results.x).reshape(3,1)    #because we have 3 parameters
y_pred = np.dot(x_train,fitted_parameters)


In [100]:
print(f' R-squared score on training data : {r2_score(y_train,y_pred)}')           

 R-squared score on training data : 0.9810086724775429


In [101]:
# Predictions for test data :

y_pred_test = np.dot(x_test,fitted_parameters)

In [102]:
print(f' R-squared score obtained from custom implementation : {r2_score(y_test,y_pred_test)}')

 R-squared score obtained from custom implementation : 0.9853660448506618


## Comparing the performance to the sklearn's inbuilt function : linear regressor

In [103]:
lr = LinearRegression()     #you create the object of class linear regression
lr.fit(x_train,y_train)     # parameters that minimize the error on training data
ypred = lr.predict(x_test)  #using parameters derived from training, you made predictions on test set.

In [104]:
print(f' R-squared score obtained from In-built function : {r2_score(y_test,ypred)}')

 R-squared score obtained from In-built function : 0.985366044850984
